name: A sample workflow call

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:
      - uses: actions/checkout@v2
      - name: Where am I?
        run: |
          echo $PWD
          ls -alrtR
